# Generated by Django 5.0.4 on 2024-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_customuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
